### ISSUE TITLE
Radio and Data JST connectors appear incorrectly drawn on External Connector Board schematic

### ISSUE THREAD

**Issue by tonycanike** [sparkfun/SparkFun_RTK_Facet#15]
As linked to from the Facet product page
   https://www.sparkfun.com/products/19984
I'm looking at 
   https://cdn.sparkfun.com/assets/d/2/a/b/0/SparkFun_RTK_Facet_-_External_Connector_Schematic.pdf
With a rev date in the title block of "12/3/2021 11:58am" and a version of "V12".

In the section of the schematic showing what I believe to be the JST Radio and Data connectors, I have the following observations:

1. I believe the "Serial Config, NMEA Out" connector is what the hookup guide calls the "Data" connector, but this isn't explicit. 

2. The hookup guide doesn't mention using the Data connector for Serial Configuration.  I always use the USB-C for serial configuration. The schematic calls it a "Serial Config..." connector.

3. Why are there two "Serial Config, NMEA Out" connectors on the schematic with the pin numbers flipped?  

4. I believe the "External Radio, RTCM In/Out" connector to be the "Radio" connector as described in the hookup guide.  Not explicit but close enough to be obvious.

5. Why are there two "External Radio, RTCM In/Out" connectors on the schematic with the pin numbers flipped?

6. According to the hookup guide, the V+ pin on both the radio and the data connector are current limited by a PTC to 600ma.  Do both connectors share the same PTC (F1) ?  That is, is the sum of the V+ current provided by the data and radio connectors limited to 600mA? This isn't explicit in the hookup guide and the schematic is unclear on this point.

I'm able to make the cables I need using the info in the hookup guide, so the issue is not an impediment for me.

**Comment by PaulZC** [comment]
Hi Tony (@tonycanike ),

Apologies. That schematic certainly isn't as clear as it could be...

On the dual connectors issue: J2 and J9 are the actual JST connectors; J12 and J11 are 4-way 0.1" pitch pads for test purposes. With hindsight, J12 and J11 should have been flipped so the pad numbers match the JST connectors. Here is the radio connector - the pads of J9 are red, the pads of J11 are green:

![image](https://github.com/sparkfun/SparkFun_RTK_Facet/assets/5690545/4e6c5ecb-a889-4d42-866d-699c3845ac7c)

The radio connector (J9) TX and RX pins are connected to the ZED-F9P UART2 and nowhere else. They can be used for an external radio module and carry RTCM data. Pin 1 provides power and is protected by a 6V 0.5A resettable fuse. On the connector schematic, the power rail is labelled as V_BATT, but it is actually the output of the soft power switch circuit on the main board. The input to the soft power circuit is the battery and USB - combined via protection diodes. With USB connected, V_BATT will be around 4.7V. With USB disconnected, V_BATT will be lower, typically 3.9V depending on the battery voltage.

The "Serial Config, NMEA Out" connector (J2) is indeed the Data connector. Apologies for the confusing label. The power on pin 1 is regulated 3.3V from the main board. I don't see a fuse in that connection. The hookup guide may need updating here. The TX and RX pins are fed by the multiplexer on the main board, the 'mode' (UART, PPS, I2C, ADC) is set in software. When the multiplexer is set to monitor the ESP32 <-> ZED-F9P UART1 signals, it is best to regard both TX and RX as outputs. You can't use the RX pin to inject data to the ZED, you can only use it to monitor what data the ESP32 is sending to the ZED. The TX pin allows you to monitor the full data stream from the ZED to the ESP32, the ESP32 forwards this to Bluetooth, ESP-Now, and WiFi and logs to SD as needed.

I hope this helps - and hasn't confused you further! Let us know if you need a better explanation or if anything is still unclear.

Best wishes,
Paul

**Comment by tonycanike** [comment]
@PaulZC , thank you, that helps a lot!  Now I understand.   And it's here for others to reference.  

Appreciate your time,  
Tony.
