### ISSUE TITLE
About Hardware and Firmware Help

### ISSUE THREAD

**Issue by Jewinn** [sparkfun/SparkFun_RTK_Facet#16]
I am creating a product based on RTK Facet, what hardware for GNSS antennas is needed for integration? Additionally, tell me what to do for firmware installation and what to do if I want to make modifications to the firmware after assembling the PCB according to the hardware file that was provided.

**Comment by nseidle** [comment]
Very exciting!

Any L1/L2 GNSS antenna should work. The Facet uses a U.FL connector on the board and provides 3.3V to the antenna.

To compile RTK Firmware, see [these docs](https://docs.sparkfun.com/SparkFun_RTK_Firmware/firmware_update/#compiling-source).

The [RTK Firmware](https://github.com/sparkfun/SparkFun_RTK_Firmware/tree/main) checks an [ADC pin at boot](https://github.com/sparkfun/SparkFun_RTK_Firmware/blob/main/Firmware/RTK_Surveyor/Begin.ino#L51) for a pair of resistors. Depending on the value, it can identify what device if present. You can either leave the hardware largely unchanged and mimic the feature set of the RTK Facet, or if you make hardware changes (move pins, add devices, etc) then you will need to add your own resistor pair value and add the functions to the firmware to support those new/added devices.

Note that most of our development is over on [RTK Everywhere](https://github.com/sparkfun/SparkFun_RTK_everywhere_Firmware). This codebase has more features but requires an ESP32 with internal PSRAM (ie, ESP32 WROVER, ESP32 Pico with PSRAM, etc).
